services:
  minio:
      container_name: minio_conatiner
      image: minio/minio
      command: server /data --console-address ":9001"
      environment:
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
        - MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
        - MINIO_API_PORT=${MINIO_API_PORT}
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - ./minio_data:/data
      restart: always